export enum ResponseMessage {
  CREATE_SUCCESS = 'CREATE_SUCCESS',
  READ_SUCCESS = 'READ_SUCCESS',
  UPDATE_SUCCESS = 'UPDATE_SUCCESS',
  DELETE_SUCCESS = 'DELETE_SUCCESS',
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  REISSUE_SUCCESS = 'REISSUE_SUCCESS',
  FOLLOW_SUCCESS = 'FOLLOW_SUCCESS',
}
