export enum ResponseMessage {
  CREATE_SUCCESS = 'CREATE_SUCCESS',
  READ_SUCCESS = 'READ_SUCCESS',
  UPDATE_SUCCESS = 'UPDATE_SUCCESS',
  DELETE_SUCCESS = 'DELETE_SUCCESS',
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGOUT_SUCCESS = 'LOGOUT_SUCCESS',
  REISSUE_SUCCESS = 'REISSUE_SUCCESS',
  FOLLOW_SUCCESS = 'FOLLOW_SUCCESS',
  UNFOLLOW_SUCCESS = 'UNFOLLOW_SUCCESS',
  BLOCK_SUCCESS = 'BLOCK_SUCCESS',
  UNBLOCK_SUCCESS = 'UNBLOCK_SUCCESS',
}
